CREATE TABLE [fias_Moscow].[House] (
    [POSTALCODE] VARCHAR (6)      NULL,
    [IFNSFL]     VARCHAR (4)      NULL,
    [TERRIFNSFL] VARCHAR (4)      NULL,
    [IFNSUL]     VARCHAR (4)      NULL,
    [TERRIFNSUL] VARCHAR (4)      NULL,
    [OKATO]      VARCHAR (11)     NULL,
    [OKTMO]      VARCHAR (11)     NULL,
    [UPDATEDATE] SMALLDATETIME    NULL,
    [HOUSENUM]   VARCHAR (20)     NULL,
    [ESTSTATUS]  INT              NOT NULL,
    [BUILDNUM]   VARCHAR (10)     NULL,
    [STRUCNUM]   VARCHAR (10)     NULL,
    [STRSTATUS]  INT              NULL,
    [HOUSEID]    UNIQUEIDENTIFIER NOT NULL,
    [HOUSEGUID]  UNIQUEIDENTIFIER NOT NULL,
    [AOGUID]     UNIQUEIDENTIFIER NULL,
    [STARTDATE]  SMALLDATETIME    NOT NULL,
    [ENDDATE]    SMALLDATETIME    NOT NULL,
    [STATSTATUS] INT              NULL,
    [NORMDOC]    UNIQUEIDENTIFIER NULL,
    [COUNTER]    INT              NULL,
    [CADNUM]     VARCHAR (100)    NULL,
    [DIVTYPE]    INT              NULL,
    CONSTRAINT [PK_House] PRIMARY KEY CLUSTERED ([HOUSEID] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20171208-143359]
    ON [fias_Moscow].[House]([HOUSEID] ASC, [HOUSEGUID] ASC, [AOGUID] ASC, [STARTDATE] ASC, [ENDDATE] ASC)
    INCLUDE([POSTALCODE], [STATSTATUS], [NORMDOC], [COUNTER], [CADNUM], [DIVTYPE], [UPDATEDATE], [HOUSENUM], [ESTSTATUS], [BUILDNUM], [STRUCNUM], [STRSTATUS], [IFNSFL], [TERRIFNSFL], [IFNSUL], [TERRIFNSUL], [OKATO], [OKTMO]);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20171208-143750]
    ON [fias_Moscow].[House]([AOGUID] ASC, [POSTALCODE] ASC, [HOUSENUM] ASC, [ESTSTATUS] ASC, [BUILDNUM] ASC, [STRUCNUM] ASC, [STRSTATUS] ASC, [HOUSEID] ASC, [HOUSEGUID] ASC, [STARTDATE] ASC, [ENDDATE] ASC, [STATSTATUS] ASC, [COUNTER] ASC);


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20180124-212750]
    ON [fias_Moscow].[House]([AOGUID] ASC)
    INCLUDE([POSTALCODE], [IFNSFL], [TERRIFNSFL], [IFNSUL], [TERRIFNSUL], [OKATO], [OKTMO], [UPDATEDATE], [HOUSENUM], [ESTSTATUS], [BUILDNUM], [STRUCNUM], [STRSTATUS], [HOUSEID], [HOUSEGUID], [STARTDATE], [ENDDATE], [STATSTATUS], [NORMDOC], [COUNTER], [CADNUM], [DIVTYPE]);


GO
CREATE NONCLUSTERED INDEX [4455]
    ON [fias_Moscow].[House]([HOUSEGUID] ASC, [STARTDATE] ASC, [ENDDATE] ASC);

