CREATE TABLE [fias_Moscow].[HouseInterval] (
    [POSTALCODE] VARCHAR (6)      NULL,
    [IFNSFL]     VARCHAR (4)      NULL,
    [TERRIFNSFL] VARCHAR (4)      NULL,
    [IFNSUL]     VARCHAR (4)      NULL,
    [TERRIFNSUL] VARCHAR (4)      NULL,
    [OKATO]      VARCHAR (11)     NULL,
    [OKTMO]      VARCHAR (11)     NULL,
    [UPDATEDATE] SMALLDATETIME    NOT NULL,
    [INTSTART]   INT              NOT NULL,
    [INTEND]     INT              NOT NULL,
    [HOUSEINTID] UNIQUEIDENTIFIER NOT NULL,
    [INTGUID]    UNIQUEIDENTIFIER NULL,
    [AOGUID]     UNIQUEIDENTIFIER NULL,
    [STARTDATE]  SMALLDATETIME    NOT NULL,
    [ENDDATE]    SMALLDATETIME    NOT NULL,
    [INTSTATUS]  INT              NULL,
    [NORMDOC]    UNIQUEIDENTIFIER NULL,
    [COUNTER]    INT              NOT NULL,
    CONSTRAINT [PK_HouseInterval] PRIMARY KEY CLUSTERED ([HOUSEINTID] ASC)
);

