CREATE TABLE [fias_Moscow].[Landmark] (
    [LOCATION]   VARCHAR (1000)   NULL,
    [REGIONCODE] VARCHAR (2)      NULL,
    [POSTALCODE] VARCHAR (6)      NULL,
    [IFNSFL]     VARCHAR (4)      NULL,
    [TERRIFNSFL] VARCHAR (4)      NULL,
    [IFNSUL]     VARCHAR (4)      NULL,
    [TERRIFNSUL] VARCHAR (4)      NULL,
    [OKATO]      VARCHAR (11)     NULL,
    [OKTMO]      VARCHAR (11)     NULL,
    [UPDATEDATE] SMALLDATETIME    NOT NULL,
    [LANDID]     VARCHAR (50)     NOT NULL,
    [LANDGUID]   VARCHAR (50)     NULL,
    [AOGUID]     UNIQUEIDENTIFIER NULL,
    [STARTDATE]  SMALLDATETIME    NOT NULL,
    [ENDDATE]    SMALLDATETIME    NOT NULL,
    [NORMDOC]    UNIQUEIDENTIFIER NULL,
    [CADNUM]     VARCHAR (1000)   NULL,
    CONSTRAINT [PK_Landmark] PRIMARY KEY CLUSTERED ([LANDID] ASC)
);

