CREATE TABLE [fias_Moscow].[Object_log] (
    [Object_log_ID]      INT              IDENTITY (1, 1) NOT NULL,
    [AOGUID]             UNIQUEIDENTIFIER NULL,
    [FORMALNAME]         NVARCHAR (120)   NULL,
    [REGIONCODE]         NVARCHAR (2)     NULL,
    [AUTOCODE]           NVARCHAR (1)     NULL,
    [AREACODE]           NVARCHAR (3)     NULL,
    [CITYCODE]           NVARCHAR (3)     NULL,
    [CTARCODE]           NVARCHAR (3)     NULL,
    [PLACECODE]          NVARCHAR (3)     NULL,
    [STREETCODE]         NVARCHAR (4)     NULL,
    [EXTRCODE]           NVARCHAR (4)     NULL,
    [SEXTCODE]           NVARCHAR (3)     NULL,
    [OFFNAME]            NVARCHAR (120)   NULL,
    [POSTALCODE]         NVARCHAR (6)     NULL,
    [IFNSFL]             NVARCHAR (4)     NULL,
    [TERRIFNSFL]         NVARCHAR (4)     NULL,
    [IFNSUL]             NVARCHAR (4)     NULL,
    [TERRIFNSUL]         NVARCHAR (4)     NULL,
    [OKATO]              NVARCHAR (11)    NULL,
    [OKTMO]              NVARCHAR (11)    NULL,
    [UPDATEDATE]         DATETIME2 (3)    NULL,
    [SHORTNAME]          NVARCHAR (10)    NULL,
    [AOLEVEL]            INT              NULL,
    [PARENTGUID]         UNIQUEIDENTIFIER NULL,
    [AOID]               UNIQUEIDENTIFIER NOT NULL,
    [PREVID]             UNIQUEIDENTIFIER NULL,
    [NEXTID]             UNIQUEIDENTIFIER NULL,
    [CODE]               NVARCHAR (17)    NULL,
    [PLAINCODE]          NVARCHAR (15)    NULL,
    [ACTSTATUS]          INT              NULL,
    [CENTSTATUS]         INT              NULL,
    [OPERSTATUS]         INT              NULL,
    [CURRSTATUS]         INT              NULL,
    [STARTDATE]          DATETIME2 (3)    NULL,
    [ENDDATE]            DATETIME2 (3)    NULL,
    [NORMDOC]            UNIQUEIDENTIFIER NULL,
    [LIVESTATUS]         NVARCHAR (1)     NULL,
    [CADNUM]             NVARCHAR (100)   NULL,
    [DIVTYPE]            INT              NULL,
    [OFFNAME_NUM_TYPE]   INT              NULL,
    [OFFNAME_NUM_NUMBER] INT              NULL,
    [OFFNAME_NUM_PREFIX] INT              NULL,
    [OFFNAME_NUMBER]     VARCHAR (20)     NULL,
    [OFFNAME_PREFIX]     VARCHAR (20)     NULL,
    [OFFNAME_NAME]       VARCHAR (80)     NULL,
    [CONVERTSTREET]      NVARCHAR (50)    NULL,
    [updated]            DATETIME         DEFAULT (getdate()) NULL,
    CONSTRAINT [PK_Key1] PRIMARY KEY CLUSTERED ([Object_log_ID] ASC)
);

