CREATE TABLE [dbo].[gu_log] (
    [id]                                                               INT            IDENTITY (1, 1) NOT NULL,
    [changedate]                                                       DATETIME       CONSTRAINT [DF_gu_log_changedate] DEFAULT (getdate()) NOT NULL,
    [kod]                                                              INT            NOT NULL,
    [project]                                                          NVARCHAR (50)  NULL,
    [num]                                                              NCHAR (10)     NULL,
    [data_montaja]                                                     DATE           NULL,
    [status]                                                           NVARCHAR (50)  NULL,
    [fio]                                                              NVARCHAR (50)  NULL,
    [fio_doljnost]                                                     NVARCHAR (50)  NULL,
    [data_v_proverku]                                                  DATE           NULL,
    [data_osmotra]                                                     DATE           NULL,
    [fact_ustanovki]                                                   NVARCHAR (50)  NULL,
    [unikalniy]                                                        NVARCHAR (50)  NULL,
    [tipgu]                                                            NVARCHAR (50)  NULL,
    [okrug]                                                            NVARCHAR (MAX) NULL,
    [ulitsa]                                                           NVARCHAR (MAX) NULL,
    [nazvanie_ulitsi]                                                  NVARCHAR (MAX) NULL,
    [dom_korp_str]                                                     NVARCHAR (50)  NULL,
    [odnostoronie_dvijenie]                                            NCHAR (10)     NULL,
    [izmerennaya_shirina_trotuara]                                     NVARCHAR (50)  NULL,
    [otsenochaya_shirina_trotuara]                                     NVARCHAR (50)  NULL,
    [rastoyanie_ot_opori]                                              NVARCHAR (50)  NULL,
    [tip_poverchnosti]                                                 NVARCHAR (50)  NULL,
    [prokhodimost]                                                     NVARCHAR (50)  NULL,
    [rekonstruktsiya]                                                  NVARCHAR (50)  NULL,
    [prosmatrivaemost]                                                 NVARCHAR (50)  NULL,
    [sostoyaniegu]                                                     NVARCHAR (50)  NULL,
    [orientatsiyagu]                                                   NVARCHAR (50)  NULL,
    [sootv_tech_pasport]                                               NVARCHAR (50)  NULL,
    [rastoyanie_do_mesta_ust_po_pasportu]                              NVARCHAR (50)  NULL,
    [po_prosmatrivaemosti]                                             NVARCHAR (50)  NULL,
    [po_shirine_trotuara_v_meste_ustanovki]                            NVARCHAR (50)  NULL,
    [po_otsutstviyu_navisaniya_nad_proezzhej_chastyu]                  NVARCHAR (50)  NULL,
    [po_raspolozheniyu_otnositelno_zelenykh_nasazhdenij]               NVARCHAR (50)  NULL,
    [po_rasstoyaniyu_ot_vkhoda_v_transportnye_uzly_i_doma]             NVARCHAR (50)  NULL,
    [po_rasstoyaniyu_do_kraya_velosipednoj_dorozhki]                   NVARCHAR (50)  NULL,
    [po_soderzhaniyu]                                                  NVARCHAR (50)  NULL,
    [po_kolichestvu_i_pravilnomu_raspolozheniyu]                       NVARCHAR (50)  NULL,
    [kolichestvo_informatsionnykh_polej]                               NCHAR (10)     NULL,
    [nalichie_modulya_s_kartoj_mestnosti]                              NVARCHAR (50)  NULL,
    [oformlenie_osnovaniya]                                            NVARCHAR (50)  NULL,
    [territoriya]                                                      NVARCHAR (50)  NULL,
    [razmer_betonnogo_bloka_dlina]                                     NVARCHAR (50)  NULL,
    [razmer_betonnogo_bloka_shirina]                                   NVARCHAR (50)  NULL,
    [ploschad_vosstanovitelnykh_rabot_posle_zaglubleniya]              NVARCHAR (50)  NULL,
    [vyvoz_tekhniki_inventarya_oborudovaniya]                          NVARCHAR (50)  NULL,
    [inye_narusheniya_trebovanij_tekhnicheskikh_pravil_k_gorodskim_uk] NVARCHAR (MAX) NULL,
    [zaklyuchenie]                                                     NVARCHAR (MAX) NULL,
    [tip_narusheniya_vneshnego_vida_i_tekhnicheskogo_sostoyaniya]      NVARCHAR (MAX) NULL,
    [data_otpravki_inforiatsii_ispolnitelyu]                           DATE           NULL,
    [egko_x]                                                           NVARCHAR (50)  NULL,
    [egko_y]                                                           NVARCHAR (50)  NULL,
    [adres_v_moskve]                                                   NCHAR (10)     NULL,
    [naimenovaniya_i_narpavleniya_ukazannye_na_inf_polyakh_verny]      NVARCHAR (50)  NULL,
    [otmetka_o_zanesenii_v_asu_inventarnyj_nomer]                      NVARCHAR (50)  NULL,
    [data_zaneseniya_informatsii_v_asu]                                DATE           NULL,
    [sotrudnik_zanesshij_dannye_v_asu]                                 NVARCHAR (50)  NULL,
    [data_ustanovki_po_grafiku]                                        DATE           NULL,
    [god_realizatsii]                                                  NCHAR (10)     NULL,
    [etap_rabot]                                                       NVARCHAR (50)  NULL,
    [proekt]                                                           NVARCHAR (50)  NULL,
    [data_montaja_plan]                                                DATE           NULL,
    [data_postupleniya_informatsiya_v_otdel_monitoringa]               DATE           NULL,
    [ploschad_betonnogo_bloka_kvm]                                     NVARCHAR (50)  NULL,
    [dolzhnost_sotrudnika_obsledovavshego_gu]                          NVARCHAR (50)  NULL,
    [dolzhnost_sotrudnika_zanesshego_nformatsiyu_v_asu]                NVARCHAR (50)  NULL,
    [prim]                                                             NVARCHAR (MAX) NULL,
    [akt_v_arkhive]                                                    NCHAR (10)     NULL,
    [inf_pole_blok_1_storona_a]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_1_storona_b]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_2_storona_a]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_2_storona_b]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_3_storona_a]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_3_storona_b]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_4_storona_a]                                        NVARCHAR (MAX) NULL,
    [inf_pole_blok_4_storona_b]                                        NVARCHAR (MAX) NULL,
    [foto_storona_a]                                                   NVARCHAR (50)  NULL,
    [foto_storona_b]                                                   NVARCHAR (50)  NULL,
    [foto_text_1]                                                      NVARCHAR (50)  NULL,
    [foto_text_2]                                                      NVARCHAR (50)  NULL,
    [foto_text_3]                                                      NVARCHAR (50)  NULL,
    [foto_text_4]                                                      NVARCHAR (50)  NULL,
    [geogr_koordinati]                                                 NVARCHAR (50)  NULL,
    [koordinati_leg]                                                   NVARCHAR (50)  NULL,
    [zamechaniya_key]                                                  INT            NULL,
    [v_plane_v_rabote]                                                 INT            NULL,
    [vse_ok_key]                                                       INT            NULL,
    [v_plane_key]                                                      INT            NULL,
    [ustraneno_key]                                                    INT            NULL,
    [akt_v_ogs_key]                                                    INT            NULL,
    [prinato_key]                                                      INT            NULL,
    [zam1_key]                                                         INT            NULL,
    [zam2_key]                                                         INT            NULL,
    [zam3_key]                                                         INT            NULL,
    [zam4_key]                                                         INT            NULL,
    [data_prinatiya]                                                   DATE           NULL,
    [obkhodchik_timer]                                                 NVARCHAR (50)  NULL,
    [zam1_text]                                                        NVARCHAR (MAX) NULL,
    [zam2_text]                                                        NVARCHAR (MAX) NULL,
    [zam3_text]                                                        NVARCHAR (MAX) NULL,
    [zam4_text]                                                        NVARCHAR (MAX) NULL,
    [zam1_foto]                                                        NVARCHAR (50)  NULL,
    [zam2_foto]                                                        NVARCHAR (50)  NULL,
    [zam3_foto]                                                        NVARCHAR (50)  NULL,
    [zam4_foto]                                                        NVARCHAR (50)  NULL,
    [memo]                                                             NVARCHAR (MAX) NULL,
    [isklucheno_key]                                                   INT            NULL,
    [isklucheno_date]                                                  DATE           NULL,
    [isklucheno_memo]                                                  NVARCHAR (MAX) NULL,
    [isklucheno_pic]                                                   NVARCHAR (50)  NULL,
    [qr]                                                               NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_gu_log] PRIMARY KEY CLUSTERED ([kod] ASC)
);

