CREATE TABLE [dbo].[reestr_log] (
    [id]                                    INT            IDENTITY (1, 1) NOT NULL,
    [changedate]                            DATETIME       DEFAULT (getdate()) NOT NULL,
    [kod]                                   INT            NOT NULL,
    [num]                                   INT            NULL,
    [project]                               VARCHAR (50)   NULL,
    [okrug]                                 VARCHAR (50)   NULL,
    [ulitsa]                                VARCHAR (50)   NULL,
    [nazvanie_ulitsi]                       VARCHAR (50)   NULL,
    [dom]                                   VARCHAR (50)   NULL,
    [korpus]                                VARCHAR (50)   NULL,
    [stroenie]                              VARCHAR (50)   NULL,
    [kategoriya]                            VARCHAR (50)   NULL,
    [dom_korp_str]                          VARCHAR (50)   NULL,
    [dom_korp_str1]                         VARCHAR (MAX)  NULL,
    [unikalniy]                             VARCHAR (50)   NULL,
    [tipdu]                                 VARCHAR (50)   NULL,
    [tipdumatc]                             VARCHAR (50)   NULL,
    [razmerdu]                              VARCHAR (50)   NULL,
    [ploshaddu]                             VARCHAR (50)   NULL,
    [ulitsadu]                              VARCHAR (50)   NULL,
    [domdu_ilion]                           VARCHAR (50)   NULL,
    [domdu]                                 VARCHAR (50)   NULL,
    [montaj]                                DATE           NULL,
    [montaj_plan]                           DATE           NULL,
    [subpodradchik]                         VARCHAR (50)   NULL,
    [date1]                                 DATE           NULL,
    [pic1]                                  VARCHAR (MAX)  NULL,
    [checkpic1]                             NCHAR (10)     NULL,
    [pic2]                                  VARCHAR (MAX)  NULL,
    [pic3]                                  VARCHAR (MAX)  NULL,
    [checkpic3]                             VARCHAR (MAX)  NULL,
    [egko_map_txt]                          VARCHAR (50)   NULL,
    [proverka_karti]                        VARCHAR (50)   NULL,
    [fio]                                   VARCHAR (50)   NULL,
    [doljnost]                              VARCHAR (50)   NULL,
    [org]                                   VARCHAR (50)   NULL,
    [history]                               VARCHAR (MAX)  NULL,
    [data_osmotra]                          DATE           NULL,
    [data_osmotra_fio]                      VARCHAR (50)   NULL,
    [data_osmotra_doljnost]                 VARCHAR (50)   NULL,
    [fact_ustanovki]                        VARCHAR (50)   NULL,
    [vospriyatie]                           VARCHAR (50)   NULL,
    [dlina_fasada]                          VARCHAR (50)   NULL,
    [koldu]                                 NCHAR (10)     NULL,
    [piktogrammi]                           VARCHAR (50)   NULL,
    [raspayachnaya_korobka]                 VARCHAR (50)   NULL,
    [nalichie_podkl]                        NCHAR (10)     NULL,
    [vozmojnost_podkl]                      NCHAR (10)     NULL,
    [demontaj]                              VARCHAR (50)   NULL,
    [vost_fasada]                           VARCHAR (50)   NULL,
    [proverka_podsveta_foto]                VARCHAR (50)   NULL,
    [data_proverka_podsveta]                DATE           NULL,
    [proverka_podsveta_sost]                VARCHAR (50)   NULL,
    [proverka_podsveta_dojnost]             VARCHAR (50)   NULL,
    [proverka_podsveta_fio]                 VARCHAR (50)   NULL,
    [sootvetstvie_tipa]                     VARCHAR (50)   NULL,
    [ust_na_linii]                          VARCHAR (50)   NULL,
    [egko_x]                                VARCHAR (50)   NULL,
    [egko_y]                                VARCHAR (50)   NULL,
    [geogr_koord]                           VARCHAR (50)   NULL,
    [egko_fio]                              NVARCHAR (MAX) NULL,
    [egko_doljnost]                         VARCHAR (50)   NULL,
    [egko_data]                             DATE           NULL,
    [tip_neobkhodimix_rabot]                VARCHAR (50)   NULL,
    [nesootv_tipa]                          VARCHAR (50)   NULL,
    [nesootv_kategorii]                     VARCHAR (50)   NULL,
    [nedemontirovan_stariy]                 VARCHAR (50)   NULL,
    [vvost_fasad]                           VARCHAR (50)   NULL,
    [ne_ustanovlen]                         VARCHAR (50)   NULL,
    [zamechaniy_net]                        VARCHAR (50)   NULL,
    [dop_zam1_text]                         NVARCHAR (MAX) NULL,
    [dop_zam2_text]                         NVARCHAR (MAX) NULL,
    [dop_zam3_text]                         NVARCHAR (MAX) NULL,
    [dop_zam4_text]                         NVARCHAR (MAX) NULL,
    [dop_zam5_text]                         NVARCHAR (MAX) NULL,
    [dop_zam6_text]                         NVARCHAR (MAX) NULL,
    [dop_zam1_key]                          VARCHAR (50)   NULL,
    [dop_zam2_key]                          VARCHAR (50)   NULL,
    [dop_zam3_key]                          VARCHAR (50)   NULL,
    [dop_zam4_key]                          VARCHAR (50)   NULL,
    [dop_zam5_key]                          VARCHAR (50)   NULL,
    [dop_zam6_key]                          VARCHAR (50)   NULL,
    [dop_zam1_pic]                          VARCHAR (50)   NULL,
    [dop_zam2_pic]                          VARCHAR (50)   NULL,
    [dop_zam3_pic]                          VARCHAR (50)   NULL,
    [dop_zam4_pic]                          VARCHAR (50)   NULL,
    [dop_zam5_pic]                          VARCHAR (50)   NULL,
    [dop_zam6_pic]                          VARCHAR (50)   NULL,
    [status]                                VARCHAR (50)   NULL,
    [status_fio]                            VARCHAR (50)   NULL,
    [data_vvoda_akt]                        DATE           NULL,
    [fio_vvoda_akt]                         VARCHAR (50)   NULL,
    [doljnost_vvoda_akt]                    VARCHAR (50)   NULL,
    [data_ekpertnogo_zakl]                  DATE           NULL,
    [nomer_ekpertnogo_zakl]                 VARCHAR (50)   NULL,
    [naimenov_ekspert_org]                  VARCHAR (50)   NULL,
    [fio_vneseniya]                         VARCHAR (50)   NULL,
    [naimenov_upr_org]                      VARCHAR (50)   NULL,
    [istochnik_dannich]                     VARCHAR (50)   NULL,
    [fio_vneseniya1]                        VARCHAR (50)   NULL,
    [oprosniy_list]                         VARCHAR (50)   NULL,
    [zakluchenie_du]                        VARCHAR (MAX)  NULL,
    [zakluchenie_du1]                       VARCHAR (MAX)  NULL,
    [k_priemke]                             VARCHAR (MAX)  NULL,
    [qr]                                    VARCHAR (50)   NULL,
    [qrpath]                                VARCHAR (50)   NULL,
    [bti_adres]                             VARCHAR (MAX)  NULL,
    [bti_naznachenie]                       VARCHAR (50)   NULL,
    [bti_god_postroyki]                     VARCHAR (50)   NULL,
    [bti_etaji]                             VARCHAR (50)   NULL,
    [bti_alt_adres]                         VARCHAR (MAX)  NULL,
    [bti_for_find]                          VARCHAR (255)  NULL,
    [memo]                                  VARCHAR (MAX)  NULL,
    [v_plane_key]                           INT            NULL,
    [osmotren_key]                          INT            NULL,
    [isklucheno_key]                        INT            NULL,
    [isklucheno_memo]                       NVARCHAR (MAX) NULL,
    [isklucheno_pic]                        NCHAR (10)     NULL,
    [isklucheno_date]                       DATE           NULL,
    [zamechaniya_key]                       INT            NULL,
    [zamechaniya_nashi_key]                 INT            NULL,
    [zamechaniya_nashi_text]                NVARCHAR (MAX) NULL,
    [zamechaniya_nashi_text_boss]           NVARCHAR (MAX) NULL,
    [akt_v_ogs_key]                         INT            NULL,
    [akt_podpisan_key]                      INT            NULL,
    [ustraneno_key]                         INT            NULL,
    [new_key]                               INT            NULL,
    [dlinafasada_key]                       INT            NULL,
    [piktogrammi_key]                       INT            NULL,
    [elektrpodkl_key]                       INT            NULL,
    [vse_ok_key]                            INT            NULL,
    [proverka_timer]                        VARCHAR (50)   NULL,
    [koordinati_timer]                      VARCHAR (50)   NULL,
    [v_plane_v_rabote]                      NVARCHAR (MAX) NULL,
    [prinato_status]                        INT            NULL,
    [prinato_data]                          DATE           NULL,
    [prinato_memo]                          NVARCHAR (MAX) NULL,
    [ustanovka_du_zam]                      NVARCHAR (MAX) NULL,
    [nesootv_tip_zam]                       NVARCHAR (MAX) NULL,
    [nesootv_kategorii_zam]                 NVARCHAR (MAX) NULL,
    [nesootv_demontirovan_zam]              NVARCHAR (MAX) NULL,
    [vostanovl_fasad_zam]                   NVARCHAR (MAX) NULL,
    [vozmojnost_el_podkl_zam]               NVARCHAR (MAX) NULL,
    [pictogrammi_zam]                       NVARCHAR (MAX) NULL,
    [podkluchenie_zam]                      NVARCHAR (MAX) NULL,
    [dlina_zam]                             NVARCHAR (MAX) NULL,
    [ustanovka_du_status]                   VARCHAR (50)   NULL,
    [nesootv_tip_status]                    VARCHAR (50)   NULL,
    [nesootv_kategorii_status]              VARCHAR (50)   NULL,
    [nesootv_demontirovan_status]           VARCHAR (50)   NULL,
    [vostanovl_fasad_status]                VARCHAR (50)   NULL,
    [vozmojnost_el_podkl_status]            VARCHAR (50)   NULL,
    [pictogrammi_status]                    VARCHAR (50)   NULL,
    [podkluchenie_status]                   VARCHAR (50)   NULL,
    [dlina_status]                          VARCHAR (50)   NULL,
    [zam1_status]                           VARCHAR (50)   NULL,
    [zam2_status]                           VARCHAR (50)   NULL,
    [zam3_status]                           VARCHAR (50)   NULL,
    [zam4_status]                           VARCHAR (50)   NULL,
    [ustanovka_du_memo]                     VARCHAR (MAX)  NULL,
    [nesootv_tip_memo]                      VARCHAR (MAX)  NULL,
    [nesootv_kategorii_memo]                VARCHAR (MAX)  NULL,
    [nesootv_demontirovan_memo]             VARCHAR (MAX)  NULL,
    [vostanovl_fasad_memo]                  VARCHAR (MAX)  NULL,
    [vozmojnost_el_podkl_memo]              VARCHAR (MAX)  NULL,
    [pictogrammi_memo]                      VARCHAR (MAX)  NULL,
    [podkluchenie_memo]                     VARCHAR (MAX)  NULL,
    [dlina_memo]                            VARCHAR (MAX)  NULL,
    [zam1_memo]                             VARCHAR (MAX)  NULL,
    [zam2_memo]                             VARCHAR (MAX)  NULL,
    [zam3_memo]                             VARCHAR (MAX)  NULL,
    [zam4_memo]                             VARCHAR (MAX)  NULL,
    [ustanovka_du_foto]                     VARCHAR (MAX)  NULL,
    [nesootv_tip_foto]                      VARCHAR (MAX)  NULL,
    [nesootv_kategorii_foto]                VARCHAR (MAX)  NULL,
    [nesootv_demontirovan_foto]             VARCHAR (MAX)  NULL,
    [vostanovl_fasad_foto]                  VARCHAR (MAX)  NULL,
    [vozmojnost_el_podkl_foto]              VARCHAR (MAX)  NULL,
    [pictogrammi_foto]                      VARCHAR (MAX)  NULL,
    [podkluchenie_foto]                     VARCHAR (MAX)  NULL,
    [dlina_foto]                            VARCHAR (MAX)  NULL,
    [zam1_foto]                             VARCHAR (MAX)  NULL,
    [zam2_foto]                             VARCHAR (MAX)  NULL,
    [zam3_foto]                             VARCHAR (MAX)  NULL,
    [zam4_foto]                             VARCHAR (MAX)  NULL,
    [podtverjd_ustanovka_du_memo]           VARCHAR (MAX)  NULL,
    [podtverjd_nesootv_tip_memo]            VARCHAR (MAX)  NULL,
    [podtverjd_nesootv_kategorii_memo]      VARCHAR (MAX)  NULL,
    [podtverjd_nesootv_demontirovan_memo]   VARCHAR (MAX)  NULL,
    [podtverjd_vostanovl_fasad_memo]        VARCHAR (MAX)  NULL,
    [podtverjd_vozmojnost_el_podkl_memo]    VARCHAR (MAX)  NULL,
    [podtverjd_pictogrammi_memo]            VARCHAR (MAX)  NULL,
    [podtverjd_podkluchenie_memo]           VARCHAR (MAX)  NULL,
    [podtverjd_dlina_memo]                  VARCHAR (MAX)  NULL,
    [podtverjd_zam1_memo]                   VARCHAR (MAX)  NULL,
    [podtverjd_zam2_memo]                   VARCHAR (MAX)  NULL,
    [podtverjd_zam3_memo]                   VARCHAR (MAX)  NULL,
    [podtverjd_zam4_memo]                   VARCHAR (MAX)  NULL,
    [podtverjd_ustanovka_du_foto]           VARCHAR (MAX)  NULL,
    [podtverjd_nesootv_tip_foto]            VARCHAR (MAX)  NULL,
    [podtverjd_nesootv_kategorii_foto]      VARCHAR (MAX)  NULL,
    [podtverjd_nesootv_demontirovan_foto]   VARCHAR (MAX)  NULL,
    [podtverjd_vostanovl_fasad_foto]        VARCHAR (MAX)  NULL,
    [podtverjd_vozmojnost_el_podkl_foto]    VARCHAR (MAX)  NULL,
    [podtverjd_pictogrammi_foto]            VARCHAR (MAX)  NULL,
    [podtverjd_podkluchenie_foto]           VARCHAR (MAX)  NULL,
    [podtverjd_dlina_foto]                  VARCHAR (MAX)  NULL,
    [podtverjd_zam1_foto]                   VARCHAR (MAX)  NULL,
    [podtverjd_zam2_foto]                   VARCHAR (MAX)  NULL,
    [podtverjd_zam3_foto]                   VARCHAR (MAX)  NULL,
    [podtverjd_zam4_foto]                   VARCHAR (MAX)  NULL,
    [podtverjd_ustanovka_du_status]         VARCHAR (50)   NULL,
    [podtverjd_nesootv_tip_status]          VARCHAR (50)   NULL,
    [podtverjd_nesootv_kategorii_status]    VARCHAR (50)   NULL,
    [podtverjd_nesootv_demontirovan_status] VARCHAR (50)   NULL,
    [podtverjd_vostanovl_fasad_status]      VARCHAR (50)   NULL,
    [podtverjd_vozmojnost_el_podkl_status]  VARCHAR (50)   NULL,
    [podtverjd_pictogrammi_status]          VARCHAR (50)   NULL,
    [podtverjd_podkluchenie_status]         VARCHAR (50)   NULL,
    [podtverjd_dlina_status]                VARCHAR (50)   NULL,
    [podtverjd_zam1_status]                 VARCHAR (50)   NULL,
    [podtverjd_zam2_status]                 VARCHAR (50)   NULL,
    [podtverjd_zam3_status]                 VARCHAR (50)   NULL,
    [podtverjd_zam4_status]                 VARCHAR (50)   NULL,
    [zakluchenie_du_history]                VARCHAR (MAX)  NULL,
    [koordinati_leg]                        VARCHAR (50)   NULL,
    [dom_marshrut]                          INT            NULL,
    [ilion_ulitsa]                          VARCHAR (50)   NULL,
    [ilion_dom]                             VARCHAR (50)   NULL,
    [data_v_proverku]                       DATE           NULL,
    [data_ustr_zam]                         DATE           NULL,
    [adres_bti_proverka]                    VARCHAR (MAX)  NULL,
    [fasad_summa]                           INT            NULL,
    [nalichie_summa]                        INT            NULL,
    [drugie_summa]                          INT            NULL,
    [montaj_summa]                          INT            NULL,
    [electrika_summa]                       INT            NULL,
    [tipdu_summa]                           INT            NULL,
    [kategoriya_summa]                      INT            NULL,
    [priznak]                               NVARCHAR (50)  NULL,
    [domdu2]                                VARCHAR (50)   NULL,
    [log_file]                              VARCHAR (MAX)  NULL,
    [vospriyatie_b]                         BIT            NULL,
    [raspayachnaya_korobka_b]               BIT            NULL,
    [dlina_fasada_b]                        BIT            NULL,
    [koldu_b]                               BIT            NULL,
    [piktogrammi_b]                         BIT            NULL,
    [nalichie_podkli_b]                     BIT            NULL,
    [nalichie_podkl_b]                      BIT            NULL,
    [vozmojnost_podkl_b]                    BIT            NULL,
    [demontaj_b]                            BIT            NULL,
    [ust_na_linii_b]                        BIT            NULL,
    [k_priemke_b]                           BIT            NULL,
    [vost_fasada_b]                         BIT            NULL,
    [sootvetstvie_tipa_b]                   BIT            NULL,
    [sootv_bti_b]                           BIT            NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

