CREATE TABLE [dbo].[reestr1] (
    [kod]                                   INT             NOT NULL,
    [num]                                   INT             NULL,
    [project]                               VARCHAR (50)    NULL,
    [Okrug]                                 NVARCHAR (5)    NOT NULL,
    [ulitsa]                                NVARCHAR (255)  NULL,
    [nazvanie_ulitsi]                       NVARCHAR (255)  NULL,
    [dom]                                   NVARCHAR (255)  NULL,
    [korpus]                                NVARCHAR (255)  NULL,
    [stroenie]                              NVARCHAR (255)  NULL,
    [kategoriya]                            VARCHAR (50)    NULL,
    [dom_korp_str]                          NVARCHAR (50)   NULL,
    [dom_korp_str1]                         NVARCHAR (255)  NULL,
    [tipdu]                                 VARCHAR (50)    NULL,
    [tipdumatc]                             VARCHAR (50)    NULL,
    [unikalniy]                             VARCHAR (50)    NULL,
    [ulitsadu]                              VARCHAR (50)    NULL,
    [domdu_ilion]                           VARCHAR (50)    NULL,
    [domdu]                                 VARCHAR (50)    NULL,
    [date1]                                 DATE            NULL,
    [pic1]                                  VARCHAR (50)    NULL,
    [checkpic1]                             NCHAR (10)      NULL,
    [pic2]                                  VARCHAR (50)    NULL,
    [pic3]                                  VARCHAR (50)    NULL,
    [checkpic3]                             VARCHAR (10)    NULL,
    [egko_map_txt]                          VARCHAR (50)    NULL,
    [proverka_karti]                        VARCHAR (50)    NULL,
    [history]                               VARCHAR (2000)  NULL,
    [data_osmotra]                          DATE            NULL,
    [data_osmotra_fio]                      VARCHAR (50)    NULL,
    [data_osmotra_doljnost]                 VARCHAR (50)    NULL,
    [fact_ustanovki]                        VARCHAR (50)    NULL,
    [vospriyatie]                           VARCHAR (50)    NULL,
    [dlina_fasada]                          VARCHAR (50)    NULL,
    [koldu]                                 VARCHAR (50)    NULL,
    [piktogrammi]                           VARCHAR (50)    NULL,
    [raspayachnaya_korobka]                 VARCHAR (50)    NULL,
    [nalichie_podkl]                        VARCHAR (50)    NULL,
    [vozmojnost_podkl]                      VARCHAR (50)    NULL,
    [demontaj]                              VARCHAR (50)    NULL,
    [vost_fasada]                           VARCHAR (50)    NULL,
    [proverka_podsveta_foto]                VARCHAR (50)    NULL,
    [data_proverka_podsveta]                DATE            NULL,
    [proverka_podsveta_sost]                VARCHAR (50)    NULL,
    [proverka_podsveta_dojnost]             VARCHAR (50)    NULL,
    [proverka_podsveta_fio]                 VARCHAR (50)    NULL,
    [sootvetstvie_tipa]                     VARCHAR (50)    NULL,
    [ust_na_linii]                          VARCHAR (50)    NULL,
    [egko_x]                                VARCHAR (50)    NULL,
    [egko_y]                                VARCHAR (50)    NULL,
    [geogr_koord]                           VARCHAR (50)    NULL,
    [egko_fio]                              VARCHAR (50)    NULL,
    [egko_doljnost]                         VARCHAR (50)    NULL,
    [egko_data]                             DATE            NULL,
    [tip_neobkhodimix_rabot]                VARCHAR (50)    NULL,
    [nesootv_tipa]                          VARCHAR (50)    NULL,
    [nesootv_kategorii]                     VARCHAR (50)    NULL,
    [nedemontirovan_stariy]                 VARCHAR (50)    NULL,
    [vvost_fasad]                           VARCHAR (50)    NULL,
    [ne_ustanovlen]                         VARCHAR (50)    NULL,
    [zamechaniy_net]                        VARCHAR (50)    NULL,
    [status]                                VARCHAR (50)    NULL,
    [data_vvoda_akt]                        DATE            NULL,
    [fio_vvoda_akt]                         VARCHAR (50)    NULL,
    [doljnost_vvoda_akt]                    VARCHAR (50)    NULL,
    [data_ekpertnogo_zakl]                  DATE            NULL,
    [nomer_ekpertnogo_zakl]                 VARCHAR (50)    NULL,
    [naimenov_ekspert_org]                  VARCHAR (50)    NULL,
    [fio_vneseniya]                         VARCHAR (50)    NULL,
    [naimenov_upr_org]                      VARCHAR (50)    NULL,
    [istochnik_dannich]                     VARCHAR (50)    NULL,
    [fio_vneseniya1]                        VARCHAR (50)    NULL,
    [oprosniy_list]                         VARCHAR (50)    NULL,
    [zakluchenie_du]                        VARCHAR (1000)  NULL,
    [zakluchenie_du1]                       VARCHAR (1000)  NULL,
    [k_priemke]                             VARCHAR (50)    NULL,
    [qr]                                    VARCHAR (50)    NULL,
    [qrpath]                                VARCHAR (50)    NULL,
    [bti_adres]                             NVARCHAR (255)  NULL,
    [bti_naznachenie]                       NVARCHAR (255)  NULL,
    [bti_god_postroyki]                     NVARCHAR (50)   NULL,
    [bti_etaji]                             NVARCHAR (50)   NULL,
    [bti_alt_adres]                         NVARCHAR (2000) NULL,
    [bti_for_find]                          NVARCHAR (255)  NULL,
    [memo]                                  VARCHAR (1000)  NULL,
    [v_plane_key]                           INT             NULL,
    [osmotren_key]                          INT             NULL,
    [isklucheno_key]                        INT             NULL,
    [isklucheno_memo]                       VARCHAR (1000)  NULL,
    [isklucheno_pic]                        NCHAR (10)      NULL,
    [isklucheno_date]                       DATE            NULL,
    [zamechaniya_key]                       INT             NULL,
    [zamechaniya_nashi_key]                 INT             NULL,
    [zamechaniya_nashi_text]                VARCHAR (2000)  NULL,
    [zamechaniya_nashi_text_boss]           VARCHAR (2000)  NULL,
    [zamechaniya_nashi_date]                DATE            NULL,
    [zamechaniya_nashi_date_ustr]           DATE            NULL,
    [akt_v_ogs_key]                         INT             NULL,
    [akt_podpisan_key]                      INT             NULL,
    [ustraneno_key]                         INT             NULL,
    [new_key]                               INT             NULL,
    [dlinafasada_key]                       INT             NULL,
    [piktogrammi_key]                       INT             NULL,
    [elektrpodkl_key]                       INT             NULL,
    [vse_ok_key]                            INT             NULL,
    [proverka_timer]                        VARCHAR (50)    NULL,
    [koordinati_timer]                      VARCHAR (50)    NULL,
    [v_plane_v_rabote]                      VARCHAR (100)   NULL,
    [prinato_status]                        INT             NULL,
    [prinato_data]                          DATE            NULL,
    [prinato_memo]                          VARCHAR (500)   NULL,
    [zakluchenie_du_history]                VARCHAR (2000)  NULL,
    [koordinati_leg]                        VARCHAR (50)    NULL,
    [dom_marshrut]                          INT             NULL,
    [ilion_ulitsa]                          NVARCHAR (255)  NULL,
    [ilion_dom]                             NVARCHAR (50)   NULL,
    [data_v_proverku]                       DATE            NULL,
    [data_ustr_zam]                         DATE            NULL,
    [adres_bti_proverka]                    NVARCHAR (255)  NULL,
    [fasad_summa]                           INT             NULL,
    [nalichie_summa]                        INT             NULL,
    [drugie_summa]                          INT             NULL,
    [montaj_summa]                          INT             NULL,
    [electrika_summa]                       INT             NULL,
    [tipdu_summa]                           INT             NULL,
    [kategoriya_summa]                      INT             NULL,
    [priznak]                               VARCHAR (50)    NULL,
    [domdu2]                                VARCHAR (50)    NULL,
    [log_file]                              VARCHAR (2000)  NULL,
    [sootv_bti]                             VARCHAR (50)    NULL,
    [kartograf_zam]                         VARCHAR (1000)  NULL,
    [dlina_foto]                            VARCHAR (255)   NULL,
    [dlina_memo]                            VARCHAR (1000)  NULL,
    [dlina_status]                          VARCHAR (50)    NULL,
    [dlina_zam]                             VARCHAR (1000)  NULL,
    [podtverjd_dlina_foto]                  VARCHAR (255)   NULL,
    [podtverjd_dlina_memo]                  VARCHAR (1000)  NULL,
    [podtverjd_dlina_status]                VARCHAR (50)    NULL,
    [dop_zam1_key]                          VARCHAR (1)     NULL,
    [dop_zam1_pic]                          VARCHAR (255)   NULL,
    [dop_zam1_text]                         VARCHAR (1000)  NULL,
    [nesootv_demontirovan_foto]             VARCHAR (255)   NULL,
    [nesootv_demontirovan_memo]             VARCHAR (1000)  NULL,
    [nesootv_demontirovan_status]           VARCHAR (50)    NULL,
    [nesootv_demontirovan_zam]              VARCHAR (1000)  NULL,
    [podtverjd_nesootv_demontirovan_foto]   VARCHAR (255)   NULL,
    [podtverjd_nesootv_demontirovan_memo]   VARCHAR (1000)  NULL,
    [podtverjd_nesootv_demontirovan_status] VARCHAR (50)    NULL,
    [nesootv_kategorii_foto]                VARCHAR (255)   NULL,
    [nesootv_kategorii_memo]                VARCHAR (1000)  NULL,
    [nesootv_kategorii_status]              VARCHAR (50)    NULL,
    [nesootv_kategorii_zam]                 VARCHAR (1000)  NULL,
    [podtverjd_nesootv_kategorii_foto]      VARCHAR (255)   NULL,
    [podtverjd_nesootv_kategorii_memo]      VARCHAR (1000)  NULL,
    [podtverjd_nesootv_kategorii_status]    VARCHAR (50)    NULL,
    [nesootv_tip_foto]                      VARCHAR (255)   NULL,
    [nesootv_tip_memo]                      VARCHAR (1000)  NULL,
    [nesootv_tip_status]                    VARCHAR (50)    NULL,
    [nesootv_tip_zam]                       VARCHAR (1000)  NULL,
    [podtverjd_nesootv_tip_foto]            VARCHAR (255)   NULL,
    [podtverjd_nesootv_tip_memo]            VARCHAR (1000)  NULL,
    [podtverjd_nesootv_tip_status]          VARCHAR (50)    NULL,
    [pictogrammi_foto]                      VARCHAR (255)   NULL,
    [pictogrammi_memo]                      VARCHAR (1000)  NULL,
    [pictogrammi_status]                    VARCHAR (50)    NULL,
    [pictogrammi_zam]                       VARCHAR (1000)  NULL,
    [podtverjd_pictogrammi_foto]            VARCHAR (255)   NULL,
    [podtverjd_pictogrammi_memo]            VARCHAR (1000)  NULL,
    [podtverjd_pictogrammi_status]          VARCHAR (50)    NULL,
    [podkluchenie_foto]                     VARCHAR (255)   NULL,
    [podkluchenie_memo]                     VARCHAR (1000)  NULL,
    [podkluchenie_status]                   VARCHAR (50)    NULL,
    [podkluchenie_zam]                      VARCHAR (1000)  NULL,
    [podtverjd_podkluchenie_foto]           VARCHAR (255)   NULL,
    [podtverjd_podkluchenie_memo]           VARCHAR (1000)  NULL,
    [podtverjd_podkluchenie_status]         VARCHAR (50)    NULL,
    [podtverjd_ustanovka_du_foto]           VARCHAR (255)   NULL,
    [podtverjd_ustanovka_du_memo]           VARCHAR (1000)  NULL,
    [podtverjd_ustanovka_du_status]         VARCHAR (50)    NULL,
    [ustanovka_du_foto]                     VARCHAR (255)   NULL,
    [ustanovka_du_memo]                     VARCHAR (1000)  NULL,
    [ustanovka_du_status]                   VARCHAR (50)    NULL,
    [ustanovka_du_zam]                      VARCHAR (1000)  NULL,
    [dop_zam2_key]                          VARCHAR (1)     NULL,
    [dop_zam2_pic]                          VARCHAR (255)   NULL,
    [dop_zam2_text]                         VARCHAR (1000)  NULL,
    [podtverjd_vostanovl_fasad_foto]        VARCHAR (255)   NULL,
    [podtverjd_vostanovl_fasad_memo]        VARCHAR (1000)  NULL,
    [podtverjd_vostanovl_fasad_status]      VARCHAR (50)    NULL,
    [vostanovl_fasad_foto]                  VARCHAR (255)   NULL,
    [vostanovl_fasad_memo]                  VARCHAR (1000)  NULL,
    [vostanovl_fasad_status]                VARCHAR (50)    NULL,
    [vostanovl_fasad_zam]                   VARCHAR (1000)  NULL,
    [podtverjd_vozmojnost_el_podkl_foto]    VARCHAR (255)   NULL,
    [podtverjd_vozmojnost_el_podkl_memo]    VARCHAR (1000)  NULL,
    [podtverjd_vozmojnost_el_podkl_status]  VARCHAR (50)    NULL,
    [vozmojnost_el_podkl_foto]              VARCHAR (255)   NULL,
    [vozmojnost_el_podkl_memo]              VARCHAR (1000)  NULL,
    [vozmojnost_el_podkl_status]            VARCHAR (50)    NULL,
    [vozmojnost_el_podkl_zam]               VARCHAR (1000)  NULL,
    [dop_zam3_key]                          VARCHAR (1)     NULL,
    [dop_zam3_pic]                          VARCHAR (255)   NULL,
    [dop_zam3_text]                         VARCHAR (1000)  NULL,
    [podtverjd_zam1_foto]                   VARCHAR (255)   NULL,
    [podtverjd_zam1_memo]                   VARCHAR (1000)  NULL,
    [podtverjd_zam1_status]                 VARCHAR (50)    NULL,
    [zam1_foto]                             VARCHAR (255)   NULL,
    [zam1_memo]                             VARCHAR (1000)  NULL,
    [zam1_status]                           VARCHAR (50)    NULL,
    [dop_zam4_key]                          VARCHAR (1)     NULL,
    [dop_zam4_pic]                          VARCHAR (255)   NULL,
    [dop_zam4_text]                         VARCHAR (1000)  NULL,
    [podtverjd_zam2_foto]                   VARCHAR (255)   NULL,
    [podtverjd_zam2_memo]                   VARCHAR (1000)  NULL,
    [podtverjd_zam2_status]                 VARCHAR (50)    NULL,
    [zam2_foto]                             VARCHAR (255)   NULL,
    [zam2_memo]                             VARCHAR (1000)  NULL,
    [zam2_status]                           VARCHAR (50)    NULL,
    [dop_zam5_key]                          VARCHAR (1)     NULL,
    [dop_zam5_pic]                          VARCHAR (255)   NULL,
    [dop_zam5_text]                         VARCHAR (1000)  NULL,
    [podtverjd_zam3_foto]                   VARCHAR (255)   NULL,
    [podtverjd_zam3_memo]                   VARCHAR (1000)  NULL,
    [podtverjd_zam3_status]                 VARCHAR (50)    NULL,
    [zam3_foto]                             VARCHAR (255)   NULL,
    [zam3_memo]                             VARCHAR (1000)  NULL,
    [zam3_status]                           VARCHAR (50)    NULL,
    [dop_zam6_key]                          VARCHAR (1)     NULL,
    [dop_zam6_pic]                          VARCHAR (255)   NULL,
    [dop_zam6_text]                         VARCHAR (1000)  NULL,
    [podtverjd_zam4_foto]                   VARCHAR (255)   NULL,
    [podtverjd_zam4_memo]                   VARCHAR (1000)  NULL,
    [podtverjd_zam4_status]                 VARCHAR (50)    NULL,
    [zam4_foto]                             VARCHAR (255)   NULL,
    [zam4_memo]                             VARCHAR (1000)  NULL,
    [zam4_status]                           VARCHAR (50)    NULL,
    [adress_id]                             INT             NOT NULL
);

