CREATE TABLE [dbo].[ТехсостояниеГУ] (
    [Уникальный номер информационного указателя]           NVARCHAR (255) NULL,
    [Округ]                                                NVARCHAR (255) NULL,
    [Нас# Пункт]                                           NVARCHAR (255) NULL,
    [Район]                                                NVARCHAR (255) NULL,
    [Улица, проспект, пер# и проч]                         NVARCHAR (255) NULL,
    [Дом, корп#, стр# и проч]                              NVARCHAR (255) NULL,
    [Ответственный]                                        NVARCHAR (255) NULL,
    [Проверено]                                            DATETIME       NULL,
    [Установлен]                                           NVARCHAR (255) NULL,
    [Аварийная конструкция]                                NVARCHAR (255) NULL,
    [Механическое повреждение опоры]                       NVARCHAR (255) NULL,
    [Сломаны информационные поля]                          NVARCHAR (255) NULL,
    [Повреждены информационные поля]                       NVARCHAR (255) NULL,
    [Сломаны направляющие информационных полей]            NVARCHAR (255) NULL,
    [Повреждены направляющие информационных полей]         NVARCHAR (255) NULL,
    [Поврежден декоративный колпак]                        NVARCHAR (255) NULL,
    [Разбит декоративный колпак]                           NVARCHAR (255) NULL,
    [Поврежден инфокуб]                                    NVARCHAR (255) NULL,
    [Отсутствует инфокуб]                                  NVARCHAR (255) NULL,
    [Наличие ржавчины на опоре]                            NVARCHAR (255) NULL,
    [Отслоение краски с опоры]                             NVARCHAR (255) NULL,
    [Отслоение краски с направляющих информационных полей] NVARCHAR (255) NULL,
    [Конструкция испачкана краской]                        NVARCHAR (255) NULL,
    [Конструкция оклеена объявлениями]                     NVARCHAR (255) NULL,
    [Загрязнение конструкции]                              NVARCHAR (255) NULL,
    [Отсутствуют заглушки отверстий в опоре]               NVARCHAR (255) NULL,
    [Не благоустроена территория]                          NVARCHAR (255) NULL,
    [Отсутствуют реквизиты]                                FLOAT (53)     NULL,
    [Неправильные реквизиты]                               NVARCHAR (255) NULL,
    [С замечаниями]                                        NVARCHAR (255) NULL,
    [Проверка]                                             NVARCHAR (255) NULL,
    [Документ]                                             NVARCHAR (255) NULL,
    [F33]                                                  NVARCHAR (255) NULL,
    [F34]                                                  NVARCHAR (255) NULL,
    [F35]                                                  NVARCHAR (255) NULL,
    [F36]                                                  NVARCHAR (255) NULL,
    [F37]                                                  NVARCHAR (255) NULL,
    [F38]                                                  NVARCHAR (255) NULL,
    [F39]                                                  NVARCHAR (255) NULL,
    [F40]                                                  NVARCHAR (255) NULL,
    [F41]                                                  NVARCHAR (255) NULL,
    [F42]                                                  NVARCHAR (255) NULL,
    [F43]                                                  NVARCHAR (255) NULL
);

