CREATE TABLE [data_mos_ru].[TMED] (
    [Id]        UNIQUEIDENTIFIER CONSTRAINT [DF_TMED_Id] DEFAULT (newid()) ROWGUIDCOL NOT NULL,
    [global_id] INT              NOT NULL,
    [TM_COMM]   NVARCHAR (4000)  NULL,
    [TM_NAMES]  NVARCHAR (4000)  NULL,
    [TM_TRANS]  NVARCHAR (4000)  NULL,
    [TM_TYPE]   NVARCHAR (4000)  NULL,
    [TM_TE]     NVARCHAR (4000)  NULL,
    [TM_KLADR]  NVARCHAR (4000)  NULL,
    [TM_NAMEF]  NVARCHAR (4000)  NULL,
    CONSTRAINT [PK_data_mos_ru.TMED] PRIMARY KEY CLUSTERED ([Id] ASC)
);

