CREATE LOGIN [Гость]
    WITH PASSWORD = N'vgrRvrcnY{jephxtyuca=|yOmsFT7_&#$!~<&pkwfqg.vrim', SID = 0x0DE07D26738F0A48ADC8B485C4D7B02C, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

