CREATE LOGIN [Иваницын М.А.]
    WITH PASSWORD = N'vgrvrcE8nrI{jepTMhxOTutcmsFT7_&#$!~<a|y pkw@fqZ:', SID = 0xA4253ACE3A2A8E479005D4CF8E8D3D22, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

