CREATE LOGIN [Кильдишев А.С.]
    WITH PASSWORD = N'vQigrvmMrYcdn{jVrBeEpJhxmsFT7_&#$!~<tzJcza|Wayp&', SID = 0xEB64A2B5ADA36D48AD06097101C877A6, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

