CREATE LOGIN [Ломаева Н.Г.]
    WITH PASSWORD = N'vJg$rvrH+0cn{jeph,?xtcZ msFT7_&#$!~<aP|Mytpkwfqg', SID = 0xC101CDD39A0CD44D92F5AC17821D45A1, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

