CREATE LOGIN [Малых А.В.]
    WITH PASSWORD = N'vgMfrvrxcn{je%VIphx$tcaDmsFT7_&#$!~<D|Lypk_tbwfq', SID = 0x2D63CD84033F024F88EBBFBFDF54B9B5, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

