CREATE LOGIN [Мешалкин А.А.]
    WITH PASSWORD = N'vW!grv}rcSn{jBepRNhx#tcamsFT7_&#$!~<|%uypHLkEwfq', SID = 0x61AE49D98E2DB24DA1656A5573D5FF05, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

