CREATE LOGIN [Митителу П.Д.]
    WITH PASSWORD = N'vFgrvrcM4n{FjephxtDcao|dmsFT7_&#$!~<y4+pkHwfqyvg', SID = 0xA5EBEC5B26E3DE41984C8F8DA3DCDA01, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

