CREATE LOGIN [Мураховская Е.С.]
    WITH PASSWORD = N'vgrf$Nvr0cn{UjJMe#ph@xtcmsFT7_&#$!~<a|ypFkw^fqMg', SID = 0xA230DEC1D7E26C4C90675AD8C2AA061C, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

