CREATE LOGIN [Ней К.Н.]
    WITH PASSWORD = N'vg5rvrj:c=n{}jephixCtc#amsFT7_&#$!~<|y1jpkwfqgvr', SID = 0xF0DFEF2DF9DAC545B171DA1E3AC7D859, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

