CREATE LOGIN [Савчук В.С.]
    WITH PASSWORD = N'vgrYvrcn{jeph xtca|ypkQwmsFT7_&#$!~<AdfqIgvxrimz', SID = 0xFE34A52AD924F847B47D1CBEB6741A1A, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

