CREATE LOGIN [Чернов И.В.]
    WITH PASSWORD = N'4rMvumgbrlvBrcneI{jephx!msFT7_&#$!~<tca|yypkwf&q', SID = 0xC6286CB367FFC84BB59486A7BDAE95CC, DEFAULT_DATABASE = [GBUMATC], DEFAULT_LANGUAGE = [русский], CHECK_POLICY = OFF;

